#!/bin/bash

#---------------------------#
# Unzip SDk to /home/ubuntu 
#---------------------------#
juju-log " unzip SDK to home/ubuntu"
unzip builder/SDKs/appengine-java-sdk-1.7.1 -d /home/ubuntu/
unzip builder/SDKs/appengine-java-sdk-1.7.5 -d /home/ubuntu/

#---------------------------#
# Unzip GWT to /home/ubuntu 
#---------------------------#
juju-log "unzip gwt to home/ubuntu"
unzip builder/SDKs/gwt-2.4.0 -d /home/ubuntu/
unzip builder/sdks/gwt-2.5.0 -d /home/ubuntu/

#------------------#
# Move libs to Ant  
#------------------#
juju-log "move libs to ant"
sudo cp builder/Libs/junit.jar /usr/share/ant/lib/junit.jar
sudo cp builder/Libs/servlet-api.jar /usr/share/ant/lib/servlet-api.jar
sudo cp builder/Libs/org.hamcrest.core_1.1.0.v20090501071000.jar /usr/share/ant/lib/org.hamcrest.core_1.1.0.v20090501071000.jar

#------------------#
# Create Jobs   
#------------------#
java -jar jenkins-cli.jar -s http://$HOSTNAME:8080/ create-job n3phele-core < /var/lib/juju/units/generic-0/charm/builder/config.xml
java -jar jenkins-cli.jar -s http://$HOSTNAME:8080/ create-job core < /var/lib/juju/units/generic-0/charm/builder/configCore.xml
